import React from 'react';
import '../style/intro.css';

function Intro() {
  return (
    <div className='design-border'>
        <div className='design-container'>
            <div className='design-row'>
                <div className='cell size-6' />
                <div className='cell size-2' />
                <div className='cell size-12' />
                <div className='cell size-6' />
                <div className='cell size-12' />
                <div className='cell size-6' />
                <div className='cell size-4' />
                <div className='cell size-2' />
                <div className='cell size-9' />
                <div className='cell size-8' />
                <div className='cell size-2' />
                <div className='cell size-6' />
                <div className='cell size-14' />
                <div className='cell size-7' />
                <div className='cell size-6' />
                <div className='cell size-13' />
                <div className='cell size-9' />
                <div className='cell size-8' />
                <div className='cell size-2' />
                <div className='cell size-6' />
            </div>
            <div className='design-row'>
                <div className='cell size-8 red' />
                <div className='cell size-6' />
                <div className='cell size-5' />
                <div className='cell size-8 blue' />
                <div className='cell size-3' />
                <div className='cell size-4' />
                <div className='cell size-4' />
                <div className='cell size-6 yellow' />
                <div className='cell size-2' />
                <div className='cell size-6' />
                <div className='cell size-6 purple' />
                <div className='cell size-3' />
                <div className='cell size-10 green' />
                <div className='cell size-9' />
                <div className='cell size-14 pink' />
                <div className='cell size-10' />
                <div className='cell size-9 orange' />
                <div className='cell size-8' />
                <div className='cell size-3' />
            </div>
            <div className='design-row'>
                <div className='cell size-12 green' />
                <div className='cell size-10' />
                <div className='cell size-12 pink' />
                <div className='cell size-4' />
                <div className='cell size-6' />
                <div className='cell size-5 orange' />
                <div className='cell size-7 ' />
                <div className='cell size-5 lblue' />
                <div className='cell size-5' />
                <div className='cell size-13 purple' />
                <div className='cell size-4' />
                <div className='cell size-10 red' />
                <div className='cell size-2 blue' />
                <div className='cell size-4 lblue' />
                <div className='cell size-5' />
                <div className='cell size-15 yellow' />
                <div className='cell size-5' />
                <div className='cell size-2' />
                <div className='cell size-2' />
            </div>
            <div className='design-row'>
                <div className='cell size-6 blue' />
                <div className='cell size-5' />
                <div className='cell size-6 yellow' />
                <div className='cell size-6' />
                <div className='cell size-5 green' />
                <div className='cell size-3' />
                <div className='cell size-5 red' />
                <div className='cell size-9' />
                <div className='cell size-5 green' />
                <div className='cell size-5' />
                <div className='cell size-5 yellow' />
                <div className='cell size-6 ' />
                <div className='cell size-5 pink' />
                <div className='cell size-3' />
                <div className='cell size-5 lblue' />
                <div className='cell size-4' />
                <div className='cell size-4 purple' />
                <div className='cell size-6 green' />
                <div className='cell orange' />
                <div className='cell size-4' />
                <div className='cell size-7 purple' />
                <div className='cell size-5' />
                <div className='cell size-7 red' />
                <div className='cell size-11' />
            </div>
            <div className='design-row'>
                <div className='cell size-6 purple' />
                <div className='cell size-11' />
                <div className='cell size-8' />
                <div className='cell size-5 orange' />
                <div className='cell size-6' />
                <div className='cell size-4 lblue' />
                <div className='cell size-9' />
                <div className='cell size-4 pink' />
                <div className='cell size-3' />
                <div className='cell size-4 blue' />
                <div className='cell size-8' />
                <div className='cell size-5 yellow' />
                <div className='cell size-5' />
                <div className='cell size-5 green' />
                <div className='cell size-7' />
                <div className='cell size-5 blue' />
                <div className='cell size-6' />
                <div className='cell size-7 green' />
                <div className='cell size-9' />
                <div className='cell size-7 red' />
                <div className='cell size-4' />
                <div className='cell size-5' />
            </div>
            <div className='design-row'>
                <div className='cell size-2' />
                <div className='cell size-6 red' />
                <div className='cell size-13' />
                <div className='cell size-7' />
                <div className='cell size-5 blue' />
                <div className='cell size-3' />
                <div className='cell size-5 yellow' />
                <div className='cell size-6' />
                <div className='cell size-6' />
                <div className='cell size-9 red' />
                <div className='cell size-4' />
                <div className='cell size-5' />
                <div className='cell size-5 red' />
                <div className='cell size-5' />
                <div className='cell size-5 blue'/>
                <div className='cell size-7' />
                <div className='cell size-5 red' />
                <div className='cell size-5' />
                <div className='cell size-6 blue' />
                <div className='cell size-7' />
                <div className='cell size-5' />
                <div className='cell size-6 yellow' />
                <div className='cell size-6' />
                <div className='cell size-6' />
            </div>
            <div className='design-row'>
                <div className='cell size-7 lblue' />
                <div className='cell size-6' />
                <div className='cell size-3' />
                <div className='cell size-4' />
                <div className='cell size-5' />
                <div className='cell size-13 purple' />
                <div className='cell size-8' />
                <div className='cell size-8' />
                <div className='cell size-6 green' />
                <div className='cell size-11' />
                <div className='cell size-5 green' />
                <div className='cell size-3' />
                <div className='cell size-5 purple' />
                <div className='cell size-9' />
                <div className='cell size-5 yellow' />
                <div className='cell size-5' />
                <div className='cell size-4 red' />
                <div className='cell size-8' />
                <div className='cell size-8' />
                <div className='cell size-4 purple' />
                <div className='cell size-7' />
                <div className='cell size-3' />
            </div>
            <div className='design-row'>
                <div className='cell size-3' />
                <div className='cell size-6 orange' />
                <div className='cell size-8' />
                <div className='cell size-6' />
                <div className='cell size-5' />
                <div className='cell size-6 pink' />
                <div className='cell size-4 green' />
                <div className='cell size-4' />
                <div className='cell size-8' />
                <div className='cell size-6' />
                <div className='cell size-4 blue' />
                <div className='cell size-12' />
                <div className='cell size-12 yellow' />
                <div className='cell size-4' />
                <div className='cell size-7' />
                <div className='cell size-5 purple' />
                <div className='cell size-5' />
                <div className='cell size-6 green' />
                <div className='cell size-6' />
                <div className='cell size-6' />
                <div className='cell size-6 red' />
                <div className='cell size-7' />
                <div className='cell size-6' />
            </div>
            <div className='design-row'>
                <div className='cell size-6 yellow' />
                <div className='cell size-3' />
                <div className='cell' />
                <div className='cell size-8' />
                <div className='cell size-4 ' />
                <div className='cell size-5 yellow' />
                <div className='cell' />
                <div className='cell size-4 blue' />
                <div className='cell size-13' />
                <div className='cell size-4' />
                <div className='cell size-4 red' />
                <div className='cell size-7' />
                <div className='cell size-4' />
                <div className='cell size-9 purple' />
                <div className='cell size-8' />
                <div className='cell size-6' />
                <div className='cell size-5 blue' />
                <div className='cell size-6' />
                <div className='cell size-7 yellow' />
                <div className='cell' />
                <div className='cell size-3' />
                <div className='cell' />
                <div className='cell size-7 green' />
                <div className='cell size-10' />
            </div>
            <div className='design-row'>
                <div className='cell size-3' />
                <div className='cell size-6 pink' />
                <div className='cell size-5' />
                <div className='cell size-6 red' />
                <div className='cell size-6 ' />
                <div className='cell size-5 lblue ' />
                <div className='cell size-4' />
                <div className='cell size-4 orange' />
                <div className='cell size-9' />
                <div className='cell size-6' />
                <div className='cell size-4 yellow' />
                <div className='cell size-7' />
                <div className='cell size-4' />
                <div className='cell size-5 blue' />
                <div className='cell size-7' />
                <div className='cell size-8' />
                <div className='cell size-2' />
                <div className='cell size-5 green' />
                <div className='cell size-8' />
                <div className='cell size-7 blue' />
                <div className='cell size-5' />
                <div className='cell size-7 purple' />
                <div className='cell size-7' />
                <div className='cell size-7' />
            </div>
            <div className='design-row'>
                <div className='cell size-2' />
                <div className='cell size-12 blue' />
                <div className='cell size-2' />
                <div className='cell size-4' />
                <div className='cell size-2' />
                <div className='cell size-5 green' />
                <div className='cell size-6' />
                <div className='cell size-4 red' />
                <div className='cell size-14' />
                <div className='cell size-4 lblue' />
                <div className='cell size-12' />
                <div className='cell size-5 red' />
                <div className='cell size-4' />
                <div className='cell size-3' />
                <div className='cell size-7' />
                <div className='cell' />
                <div className='cell size-5 red' />
                <div className='cell size-11' />
                <div className='cell size-15 red' />
                <div className='cell size-3' />
                <div className='cell size-3' />
                <div className='cell size-6' />
            </div>
            <div className='design-row'>
                <div className='cell size-5' />
                <div className='cell size-8 yellow' />
                <div className='cell size-12' />
                <div className='cell size-5 blue' />
                <div className='cell size-8' />
                <div className='cell size-4 purple' />
                <div className='cell size-6' />
                <div className='cell size-3' />
                <div className='cell size-8 blue' />
                <div className='cell size-10' />
                <div className='cell size-7 green' />
                <div className='cell size-3' />
                <div className='cell size-6' />
                <div className='cell size-5' />
                <div className='cell size-7 yellow' />
                <div className='cell size-2' />
                <div className='cell size-6' />
                <div className='cell size-3' />
                <div className='cell size-9 green' />
                <div className='cell size-6' />
                <div className='cell size-5' />
                <div className='cell size-5' />
            </div>
            <div className='design-row'>
                <div className='cell size-4' />
                <div className='cell size-8' />
                <div className='cell size-4' />
                <div className='cell size-14' />
                <div className='cell size-2' />
                <div className='cell size-6' />
                <div className='cell size-14' />
                <div className='cell size-7' />
                <div className='cell size-6' />
                <div className='cell size-13' />
                <div className='cell size-9' />
                <div className='cell size-8' />
                <div className='cell size-2' />
                <div className='cell size-9' />
                <div className='cell size-8' />
                <div className='cell size-2' />
                <div className='cell size-6' />
                <div className='cell size-9' />
                <div className='cell size-8' />
                <div className='cell size-2' />
                <div className='cell size-6' />
            </div>
        </div>
    </div>
  )
}

export default Intro